(defun c:ZToZero (/)
  (setq ss (ssget "_X" (list (cons 0 "POINT")))) ; search all objects "POINT" in scene
  (setq i 0)
  (while (< i (sslength ss))
    (progn
      (setq le (ssname ss i))
      (setq ob (entget le))
      (setq x (nth 0 (cdr (assoc 10 ob))))
      (setq y (nth 1 (cdr (assoc 10 ob))))
      (setq ob (subst (list 10 x y 0) (assoc 10 ob) ob))
      (entmod ob)
      (entupd le)
      (setq i (+ i 1))
      )
    )
  )